name = "WeenieCraft 1.21.11"
author = "Karteufel"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d769ad35a2277a667cf606be98bcbd41048f6db3538d6c70e242771c99cb09c2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
